import type { Metadata } from "next";
import { Poiret_One, Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar/Navbar";
import Footer from "@/components/Footer";
import CartSidebarView from "../components/Cart/cart-sidebar-view";
import { Providers } from "../_providers/Providers";
import { AuthModal } from "../components/Auth/AuthModal";


const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  // display: "swap",
  // weight: "400"
});

const poiretOne = Poiret_One({
  variable: "--font-poiret-one",
  subsets: ["latin"],
  // display: "swap",
  weight: "400"
});


export const metadata: Metadata = {
  title: "Borcelle - Perfumes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col min-h-screen ${poiretOne.variable} ${montserrat.variable} font-montserrat antialiased`}
      >
        <Providers>
            <Navbar />
            <div className="flex-grow">
              {children}
            </div>
            <CartSidebarView />
            <AuthModal />
            <Footer />
        </Providers>
      </body>
    </html>
  );
}
